In [1]:
import sys
from pathlib import Path

sys.path.append(str(Path("../src").resolve()))

In [2]:
from dataset_generator import (
    generate_state_week_grid,
    generate_channel_activity,
    generate_calendar_features,
    generate_true_media_effects,
    generate_sales,
    generate_weekly_spends
)

In [3]:
df = generate_state_week_grid()

df = generate_channel_activity(df)

df = generate_calendar_features(df)

media_df = generate_true_media_effects(df)

df = generate_sales(df, media_df)

weekly_spends = generate_weekly_spends(df)

In [4]:
df[["State", "Week", "Sales"]].head(20)

             State       Week  Sales
0   Andhra Pradesh 2023-01-02    564
1   Andhra Pradesh 2023-01-09    720
2   Andhra Pradesh 2023-01-16    833
3   Andhra Pradesh 2023-01-23    880
4   Andhra Pradesh 2023-01-30    870
5   Andhra Pradesh 2023-02-06    831
6   Andhra Pradesh 2023-02-13    849
7   Andhra Pradesh 2023-02-20    856
8   Andhra Pradesh 2023-02-27    909
9   Andhra Pradesh 2023-03-06    854
10  Andhra Pradesh 2023-03-13    865
11  Andhra Pradesh 2023-03-20    876
12  Andhra Pradesh 2023-03-27   1051
13  Andhra Pradesh 2023-04-03    955
14  Andhra Pradesh 2023-04-10    911
15  Andhra Pradesh 2023-04-17    860
16  Andhra Pradesh 2023-04-24    922
17  Andhra Pradesh 2023-05-01    867
18  Andhra Pradesh 2023-05-08    889
19  Andhra Pradesh 2023-05-15    877

In [4]:
weekly_spends.head()

      Channel       Week         Spend
0  Salesforce 2023-01-02  2.832299e+07
1       Email 2023-01-02  3.445815e+05
2     Website 2023-01-02  3.058262e+05
3          TV 2023-01-02  1.274773e+08
4        Meta 2023-01-02  3.998235e+06

In [5]:
from pathlib import Path

output_folder = Path("../data/raw")

output_folder.mkdir(
    parents=True,
    exist_ok=True
)

df.to_csv(
    output_folder / "raw_data.csv",
    index=False
)

weekly_spends.to_csv(
    output_folder / "weekly_spends.csv",
    index=False
)

print("Datasets saved successfully!")

Datasets saved successfully!